baseURL = "https://blog.ctfis.art"
languageCode = "en-gb"
title = "CTF is Art"
theme = "kiss"

[minify]
minifyOutput = true

[params.info]
homeTitle = "CTF is Art"
poweredby = true

[params.rss]
placeholder = "placeholder"

[params.social]
rss = "index.xml"

[params.social.config]
platforms = ["rss"]
