baseURL = "https://blog.ctfis.art"
languageCode = "en-gb"
title = "CTF is Art"
theme = "ctfisart"
disableKinds = ["section", "taxonomy", "term"]

[taxonomies]
tag = "tags"

[params]
footer = "Subscribe to <a href=\"/index.xml\">RSS</a>."
